-- Migration: Import z80code projects batch 1
-- Projects 1 to 2
-- Generated: 2026-01-25T21:43:30.182392

-- Project 1: barbapapa_lw_playerconfig by Tronic
DO $$
DECLARE
  project_uuid uuid := gen_random_uuid();
  tag_uuid uuid;
BEGIN
  INSERT INTO projects (id, user_id, name, description, visibility, is_library, is_sticky, created_at, updated_at)
  VALUES (
    project_uuid,
    'bd6a166d-e0bf-4374-94c3-5222e517d75c'::uuid,
    'barbapapa_lw_playerconfig',
    'Imported from z80Code. Author: Tronic. Generated by Arkos Tracker 2.',
    'public',
    false,
    false,
    '2019-10-25T15:56:30.408000'::timestamptz,
    '2021-06-16T12:16:43.681000'::timestamptz
  );

  INSERT INTO project_files (project_id, name, content, is_main, "order")
  VALUES (
    project_uuid,
    'main.asm',
    '; Configuration that can be included to Arkos Tracker 2 players.
; It indicates what parts of code are useful to the song/sound effects, to save both memory and CPU.
; The players may or may not take advantage of these flags, it is up to them.

; You can either:
; - Include this to the source that also includes the player (BEFORE the player is included) (recommended solution).
; - Include this at the beginning of the player code.
; - Copy/paste this directly in the player.
; If you use one player but several songs, don''t worry, these declarations will stack up.
; If no configuration is used, the player will use default values (full code used).

	PLY_CFG_ConfigurationIsPresent = 1
	PLY_CFG_UseSpeedTracks = 1
	PLY_CFG_UseEffects = 1
	PLY_CFG_NoSoftNoHard = 1
	PLY_CFG_SoftOnly = 1
	PLY_CFG_UseEffect_SetVolume = 1
',
    true,
    0
  );

  -- Add z80code tag
  SELECT id INTO tag_uuid FROM tags WHERE name = 'z80code';
  IF tag_uuid IS NOT NULL THEN
    INSERT INTO project_tags (project_id, tag_id) VALUES (project_uuid, tag_uuid);
  END IF;
END $$;

-- Project 2: program377 by gurneyh
DO $$
DECLARE
  project_uuid uuid := gen_random_uuid();
  tag_uuid uuid;
BEGIN
  INSERT INTO projects (id, user_id, name, description, visibility, is_library, is_sticky, created_at, updated_at)
  VALUES (
    project_uuid,
    'bd6a166d-e0bf-4374-94c3-5222e517d75c'::uuid,
    'program377',
    'Imported from z80Code. Author: gurneyh. get matrix without firmware',
    'public',
    false,
    false,
    '2023-05-06T12:45:34.667000'::timestamptz,
    '2023-05-06T13:12:15.500000'::timestamptz
  );

  INSERT INTO project_files (project_id, name, content, is_main, "order")
  VALUES (
    project_uuid,
    'main.asm',
    'SCR
.NEXT_LINE      equ #bc26
.SET_MODE       equ #bc0e

                org #4000
		
start           
		        di
                ; http://quasar.cpcscene.net/doku.php?id=assem:gate_array
		        ; select low rom and mode 2
		        ld bc, #7F8a
		         out (c),c
                
                ; #3800 is return by GET_MATRIX
               	ld hl, #3800 
                ld de, T_CARAC
                ld bc, 8 * 256
                ldir
   		
		        ; deselect low rom and keep mode 2
                ld bc, #7F8e
		        out (c),c
           	
		        ei
                
                
                
; ----------------------------------------------------
;  Simple example of usage
; ----------------------------------------------------

                ld a, 2
                call SCR.SET_MODE
                
                ; for exemple, we display the ''a''
                ld a, ''A''
                call draw_char

infinite
                jr infinite
                
                
                
                
draw_char
                
                ld l, a
                ld h, 0
                ; a x 8
                add hl, hl
                add hl, hl 
                add hl, hl
                ; here hl = a * 8
                ld de, T_CARAC
                add hl, de
                ex de, hl
                ; here de, points to the address of 
                ; letter ''a''
                
                ld hl, #c000
                ld b, 8
loop            ld a, (de): inc de
                ld (hl), a
                
                call SCR.NEXT_LINE
                
                djnz loop
                ret
                
                
                
 T_CARAC',
    true,
    0
  );

  -- Add z80code tag
  SELECT id INTO tag_uuid FROM tags WHERE name = 'z80code';
  IF tag_uuid IS NOT NULL THEN
    INSERT INTO project_tags (project_id, tag_id) VALUES (project_uuid, tag_uuid);
  END IF;
END $$;
